baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "base16"
pygmentsCodeFences = true
pygmentsUseClasses = true
pygmentsCodeFencesGuessSyntax = true
lastmod = [":fileModTime", ":default"]

[params]
  custom_CSS = ["css/custom.css"]
